Repository hwi/HWIOAuthBundle, pull requests merged in 2021-12, with the labels that each got.

#1832 Remove Google Moments API from docs
  Resources/doc/resource_owners/google.md
Labels: Documentation

#1833 Bugfix | Symfony 5.4 problems
  .github/workflows/ci.yaml
  DependencyInjection/HWIOAuthExtension.php
  README.md
  Security/Core/Authentication/Token/AbstractOAuthToken.php
  Security/Core/Exception/AccountNotLinkedException.php
  composer.json
Labels: Bugfix

#1800 Maintain | Add support for Symfony 6
  CHANGELOG.md
  Controller/ConnectController.php
  DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php
  DependencyInjection/Security/Factory/OAuthFactory.php
  HWIOAuthBundle.php
  README.md
  Resources/config/controller.xml
  Resources/config/oauth.xml
  Security/Core/Authentication/Provider/OAuthProvider.php
  Security/Core/Authentication/Token/AbstractOAuthToken.php
  Security/Core/Exception/AccountNotLinkedException.php
  Security/Core/User/EntityUserProvider.php
  Security/Core/User/OAuthAwareUserProviderInterface.php
  Security/Core/User/OAuthUserProvider.php
  Security/Http/Authenticator/OAuthAuthenticator.php
  Security/Http/Firewall/OAuthListener.php
  Templating/Helper/OAuthHelper.php
  Tests/App/AppKernel.php
  Tests/App/UserProvider.php
  Tests/App/config.yml
  Tests/App/security_v4.yaml
  Tests/App/security_v6.yaml
  Tests/Controller/AbstractConnectControllerTest.php
  Tests/Controller/ConnectControllerRegistrationActionTest.php
  Tests/Fixtures/CustomUserResponse.php
  Tests/Fixtures/MyCustomProvider.php
  Tests/Fixtures/OAuthAwareException.php
  Tests/Fixtures/User.php
  Tests/Functional/AuthenticationHelperTrait.php
  Tests/Functional/Controller/ConnectControllerTest.php
  Tests/Functional/Controller/LoginControllerTest.php
  Tests/Functional/IntegrationTest.php
  Tests/OAuth/ResourceOwner/ResourceOwnerTestCase.php
  Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
  Tests/Security/Core/Authentication/Token/OAuthTokenTest.php
  Tests/Security/Core/User/EntityUserProviderTest.php
  Tests/Security/Core/User/OAuthUserProviderTest.php
  Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php
  Tests/Security/OAuthUtilsTest.php
  composer.json
Labels: Enhancement

#1839 Bugfix | Test BC layer for Symfony Security <5.4
  .github/workflows/ci.yaml
  DependencyInjection/Security/Factory/OAuthAuthenticatorFactory.php
  Security/Http/Authenticator/OAuthAuthenticator.php
  Security/Http/EntryPoint/OAuthEntryPoint.php
  Security/Http/Firewall/OAuthListener.php
  Tests/App/AppKernel.php
  Tests/App/config/security_v5_bc.yaml
  Tests/App/config/security_v6.yaml
  Tests/Security/Http/Authenticator/OAuthAuthenticatorTest.php
Labels: Bugfix

#1841 Bugfix | Restore wrongly moved `AbstractOAuthToken::getCredentials()`
  Security/Core/Authentication/Token/AbstractOAuthToken.php
  Security/Core/Authentication/Token/OAuthToken.php
Labels: Bugfix

#1844 Bugfix | Fixed issue when `connect` configuration is not set but `ConnectController` was used
  Controller/ConnectController.php
  DependencyInjection/HWIOAuthExtension.php
  Resources/config/controller.xml
  Tests/Controller/AbstractConnectControllerTest.php
  Tests/Controller/RedirectToServiceControllerTest.php
  Tests/DependencyInjection/HWIOAuthExtensionTest.php
Labels: Bugfix

#1846 Bugfix | Added missing `RememberMeBadge` into OAuth passport
  Security/Http/Authenticator/OAuthAuthenticator.php
Labels: Bugfix

#1855 Allow null User for refreshing oauth token
  src/Security/Core/Authentication/Provider/OAuthProvider.php
  tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
Labels: Bugfix

#1865 Maintain | Added new Composer 2.2 config for "allow-plugins"
  composer.json
Labels: Bugfix
