Repository hwi/HWIOAuthBundle, pull requests merged in 2021-08, with the labels that each got.

#1766 Maintain | Remove `Makefile` in favour of composer scripts
  .github/workflows/ci.yaml
  Makefile
  composer.json
Labels: Enhancement

#1741 make twig extension lazy by using a Runtime
  CHANGELOG.md
  Resources/config/twig.xml
  Security/OAuthUtils.php
  Templating/Helper/OAuthHelper.php
  Twig/Extension/OAuthExtension.php
  Twig/Extension/OAuthRuntime.php
  composer.json
Labels: Enhancement

#1768 Don't re-use creation date from previous token if was already expired in `OAuthProvider`
  Security/Core/Authentication/Provider/OAuthProvider.php
  Tests/Security/Core/Authentication/Provider/OAuthProviderTest.php
Labels: Bugfix

#1770 bump to phpstan level 3
  OAuth/Response/LinkedinUserResponse.php
  OAuth/Response/SensioConnectUserResponse.php
  OAuth/Response/UserResponseInterface.php
  Security/Core/Authentication/Token/AbstractOAuthToken.php
  Security/Http/Authenticator/OAuthAuthenticator.php
  Tests/Controller/LoginControllerTest.php
  Tests/DependencyInjection/HWIOAuthExtensionTest.php
  Tests/Fixtures/OAuthAwareException.php
  Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php
  phpstan.neon
Labels: DX, Enhancement

#1771 Maintain | Adjust codebase to match PHPStan level 5
  Controller/ConnectController.php
  Controller/RedirectToServiceController.php
  Event/FilterUserResponseEvent.php
  OAuth/Exception/HttpTransportException.php
  OAuth/ResourceOwner/DropboxResourceOwner.php
  OAuth/ResourceOwner/GenericOAuth1ResourceOwner.php
  OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php
  OAuth/ResourceOwner/JiraResourceOwner.php
  OAuth/ResourceOwner/VkontakteResourceOwner.php
  OAuth/ResourceOwnerInterface.php
  OAuth/Response/LinkedinUserResponse.php
  OAuth/Response/PathUserResponse.php
  OAuth/Response/SensioConnectUserResponse.php
  Security/Core/User/EntityUserProvider.php
  Security/Http/EntryPoint/OAuthEntryPoint.php
  Tests/Controller/ConnectControllerRegistrationActionTest.php
  phpstan.neon
Labels: DX, Enhancement

#1773 Use type hints and return types in ResourceOwnerMapInterface
  CHANGELOG.md
  Security/Http/ResourceOwnerMap.php
  Security/Http/ResourceOwnerMapInterface.php
Labels: DX, Enhancement

#1777 Create SECURITY.md
  SECURITY.md
Labels: DX

#1775 Rework ResourceOwnerMap to use service locator instead of whole DI container
  CHANGELOG.md
  DependencyInjection/CompilerPass/SetResourceOwnerServiceNameCompilerPass.php
  DependencyInjection/HWIOAuthExtension.php
  DependencyInjection/Security/Factory/OAuthFactory.php
  HWIOAuthBundle.php
  OAuth/ResourceOwner/AbstractResourceOwner.php
  OAuth/ResourceOwnerInterface.php
  Resources/config/oauth.xml
  Resources/config/resource_owners.xml
  Security/Http/ResourceOwnerMap.php
  Tests/DependencyInjection/HWIOAuthExtensionTest.php
  Tests/OAuth/ResourceOwner/GenericOAuth1ResourceOwnerTest.php
  Tests/OAuth/ResourceOwner/GenericOAuth2ResourceOwnerTest.php
Labels: DX, Enhancement

#1780 Remove "final" parameter from `FOSUBUserProvider`
  Security/Core/User/FOSUBUserProvider.php
Labels: Bugfix

#1782 Bugfix | Prevent issue with missing parameter when `connect` option is not enabled
  DependencyInjection/HWIOAuthExtension.php
Labels: Bugfix

#1769 Maintain | Added PHP 8.1 to testing matrix
  .github/workflows/ci.yaml
  composer.json
Labels: Enhancement

#1785 Bugfix | Remove "abstract=true" from non-abstract service definitions
  Resources/config/oauth.xml
  Security/Http/Firewall/OAuthListener.php
Labels: Bugfix

#1789 Maintain | Update min. Twig version to work with PHP 8
  composer.json
Labels: Bugfix

#1790 Update Yahoo resource owner to use OAuth2
  OAuth/ResourceOwner/YahooResourceOwner.php
  Resources/doc/resource_owners/yahoo.md
  Tests/OAuth/ResourceOwner/YahooResourceOwnerTest.php
Labels: Enhancement

#1792 [2.x] Fix HTTP client definition
  Resources/config/util.xml
Labels: Bugfix
